export const iconDescriptions = {
  // Day icons (1-99) in ascending order
  "1": "clear",
  "2": "mostly clear",
  "4": "partly cloudy",
  "6": "mostly cloudy",
  "7": "cloudy",
  "9": "fog",
  "11": "drizzle",
  "14": "freezing drizzle",
  "17": "freezing rain",
  "21": "isolated rain showers",
  "24": "showers in places",
  "27": "showers",
  "31": "partly cloudy with occasional light rain",
  "32": "partly cloudy with occasional moderate rain",
  "33": "partly cloudy with occasional heavy rain",
  "34": "mostly cloudy with occasional light rain",
  "35": "mostly cloudy with occasional moderate rain",
  "36": "mostly cloudy with occasional heavy rain",
  "37": "light rain",
  "38": "moderate rainfall",
  "39": "heavy rain",
  "41": "partly cloudy with occasional light sleet or sleet showers",
  "42": "partly cloudy with occasional moderate sleet or sleet showers",
  "43": "partly cloudy with occasional heavy sleet or sleet showers",
  "44": "mostly cloudy with occasional light sleet or snow showers",
  "45": "mostly cloudy with occasional moderate sleet or snow showers",
  "46": "mostly cloudy with occasional heavy sleet or sleet showers",
  "47": "light sleet",
  "48": "moderate sleet",
  "49": "heavy sleet",
  "51": "partly cloudy with occasional light snowfall or snow showers",
  "52": "partly cloudy with occasional moderate snowfall or snow showers",
  "53": "partly cloudy with occasional heavy snowfall or snow showers",
  "54": "mostly cloudy with occasional light snow or sleet",
  "55": "mostly cloudy with occasional moderate snowfall or snow showers",
  "56": "mostly cloudy with occasional heavy snowfall or snow showers",
  "57": "light snowfall",
  "58": "moderate snowfall",
  "59": "heavy snowfall",
  "61": "isolated hailstorms",
  "64": "hail showers in places",
  "67": "hailstorms",
  "71": "isolated thunderstorms",
  "74": "thunderstorms in places",
  "77": "thunderstorms",

  // Night icons (100+) in ascending order
  "101": "clear Night",
  "102": "mostly clear Night",
  "104": "partly cloudy Night",
  "106": "mostly cloudy Night",
  "107": "cloudy Night",
  "109": "fog Night",
  "111": "drizzle Night",
  "114": "freezing drizzle Night",
  "117": "freezing rain Night",
  "121": "isolated rain showers Night",
  "124": "showers in places Night",
  "127": "showers Night",
  "131": "partly cloudy with occasional light rain Night",
  "132": "partly cloudy with occasional moderate rain Night",
  "133": "partly cloudy with occasional heavy rain Night",
  "134": "mostly cloudy with occasional light rain Night",
  "135": "mostly cloudy with occasional moderate rain Night",
  "136": "mostly cloudy with occasional heavy rain Night",
  "137": "light rain Night",
  "138": "moderate rainfall Night",
  "139": "heavy rain Night",
  "141": "partly cloudy with occasional light sleet or sleet showers Night",
  "142": "partly cloudy with occasional moderate sleet or sleet showers Night",
  "143": "partly cloudy with occasional heavy sleet or sleet showers Night",
  "144": "mostly cloudy with occasional light sleet or snow showers Night",
  "145": "mostly cloudy with occasional moderate sleet or snow showers Night",
  "146": "mostly cloudy with occasional heavy sleet or sleet showers Night",
  "147": "light sleet Night",
  "148": "moderate sleet Night",
  "149": "heavy sleet Night",
  "151": "partly cloudy with occasional light snowfall or snow showers Night",
  "152": "partly cloudy with occasional moderate snowfall or snow showers Night",
  "153": "partly cloudy with occasional heavy snowfall or snow showers Night",
  "154": "mostly cloudy with occasional light snow or sleet Night",
  "155": "mostly cloudy with occasional moderate snowfall or snow showers Night",
  "156": "mostly cloudy with occasional heavy snowfall or snow showers Night",
  "157": "light snowfall Night",
  "158": "moderate snowfall Night",
  "159": "heavy snowfall Night",
  "161": "isolated hailstorMove thems Night",
  "164": "hail showers in places Night",
  "167": "hailstorms Night",
  "171": "isolated thunderstorms Night",
  "174": "thunderstorms in places Night",
  "177": "thunderstorms Night",
};

